// Code generated by go-swagger; DO NOT EDIT.

// This file is part of Instagram Stories Generator
// Copyright (c) 2020 Lenin Alevski Huerta Arias.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package user_api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Alevsk/instagram-stories/models"
)

// StoryCreateOKCode is the HTTP code returned for type StoryCreateOK
const StoryCreateOKCode int = 200

/*StoryCreateOK A successful response.

swagger:response storyCreateOK
*/
type StoryCreateOK struct {
}

// NewStoryCreateOK creates StoryCreateOK with default headers values
func NewStoryCreateOK() *StoryCreateOK {

	return &StoryCreateOK{}
}

// WriteResponse to the client
func (o *StoryCreateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*StoryCreateDefault Generic error response.

swagger:response storyCreateDefault
*/
type StoryCreateDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewStoryCreateDefault creates StoryCreateDefault with default headers values
func NewStoryCreateDefault(code int) *StoryCreateDefault {
	if code <= 0 {
		code = 500
	}

	return &StoryCreateDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the story create default response
func (o *StoryCreateDefault) WithStatusCode(code int) *StoryCreateDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the story create default response
func (o *StoryCreateDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the story create default response
func (o *StoryCreateDefault) WithPayload(payload *models.Error) *StoryCreateDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the story create default response
func (o *StoryCreateDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StoryCreateDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
